# Generated by Django 6.0.3 on 2026-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmaster',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='unitmaster',
            name='unit_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='unitmaster',
            table='purchase_master_unitmaster',
        ),
    ]
