# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0002_alter_unitmaster_options_alter_unitmaster_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardbom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_master.productcreation'),
        ),
        migrations.AddField(
            model_name='standardbom',
            name='semi_finished',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_master.itemmaster'),
        ),
    ]
