# Generated by Django 6.0.3 on 2026-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0005_product_lookup_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('customer_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('customer_category', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer_category',
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('updated_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'expense_category',
            },
        ),
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('category_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('updated_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'expense_sub_category',
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('payment_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('is_delete', models.IntegerField(default=0)),
                ('updated_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
    ]
