# Generated by Django 6.0.3 on 2026-06-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0006_customercategory_expensecategory_expensesubcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmaster',
            options={'ordering': ['item_code']},
        ),
        migrations.AlterUniqueTogether(
            name='itemmaster',
            unique_together={('group', 'sub_group', 'category', 'item_name')},
        ),
    ]
