# Generated by Django 6.0.3 on 2026-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0008_product_creation_dedicated_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcreationgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcreationsubgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
