# Generated manually for test-only purchase_entrys database setup.

import uuid
from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RateOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("supplier_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_name", models.CharField(blank=True, max_length=255, null=True)),
                ("company_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("project_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("items_data", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20)),
                ("approval_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("approval_remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by_id", models.IntegerField(blank=True, null=True)),
                ("rejected_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("supplier_code", models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("gst_no", models.CharField(blank=True, max_length=20, null=True)),
                ("pan_no", models.CharField(blank=True, max_length=20, null=True)),
                ("msme_type", models.CharField(blank=True, max_length=100, null=True)),
                ("msme_no", models.CharField(blank=True, max_length=50, null=True)),
                ("contact_person", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("po_number", models.CharField(blank=True, max_length=100, unique=True)),
                ("company_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("project_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_name", models.CharField(blank=True, max_length=255, null=True)),
                ("items_data", models.JSONField(blank=True, default=list)),
                ("po_type", models.CharField(blank=True, max_length=50, null=True)),
                ("pr_number", models.CharField(blank=True, max_length=100, null=True)),
                ("from_company", models.BooleanField(default=False)),
                ("entry_date", models.DateField(default=django.utils.timezone.localdate)),
                ("supplier_gst_no", models.CharField(blank=True, max_length=20, null=True)),
                ("supplier_pan_no", models.CharField(blank=True, max_length=20, null=True)),
                ("supplier_msme_type", models.CharField(blank=True, max_length=100, null=True)),
                ("supplier_msme_no", models.CharField(blank=True, max_length=50, null=True)),
                ("supplier_contact_person", models.CharField(blank=True, max_length=255, null=True)),
                ("supplier_contact_no", models.CharField(blank=True, max_length=20, null=True)),
                ("quotation_no", models.CharField(blank=True, max_length=100, null=True)),
                ("quotation_date", models.DateField(blank=True, null=True)),
                ("revision_no", models.CharField(default="REV001", max_length=50)),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("revision_remarks", models.TextField(blank=True, null=True)),
                ("total_basic_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("freight_charges", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("freight_tax_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("freight_tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("other_charges", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("other_tax_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("other_tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("packing_forwarding", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("packing_tax_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("packing_tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("round_off", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("total_gst_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("gross_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("payment_days", models.CharField(blank=True, max_length=255, null=True)),
                ("other_terms_conditions", models.TextField(blank=True, null=True)),
                ("shipping_address", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("workflow_status", models.CharField(choices=[("draft", "Draft"), ("pending_l1", "Pending (L1)"), ("approved_l1", "Approved (L1)"), ("rejected_l1", "Rejected (L1)"), ("approved_l2", "Approved (L2)"), ("rejected_l2", "Rejected (L2)"), ("approved_l3", "Approved (L3)"), ("rejected_l3", "Rejected (L3)")], default="pending_l1", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-entry_date", "-id"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("pr_number", models.CharField(blank=True, max_length=100, unique=True)),
                ("company_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("project_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("requisition_for", models.CharField(max_length=100)),
                ("requisition_type", models.CharField(max_length=100)),
                ("requisition_date", models.DateField()),
                ("items_data", models.JSONField(blank=True, default=list)),
                ("requested_by", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("foreclosed", "Foreclosed"), ("po_raised", "PO Raised")], default="pending", max_length=20)),
                ("level1_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level1_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level1_remarks", models.TextField(blank=True, null=True)),
                ("level2_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level2_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level2_remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level1_approved_by_id", models.IntegerField(blank=True, null=True)),
                ("level2_approved_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PurchaseOrderDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("document_type", models.CharField(max_length=100)),
                ("document_name", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="procurement/purchase-orders/documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="purchase_entrys.purchaseorder")),
            ],
            options={"ordering": ["-created_at", "-id"], "abstract": False},
        ),
        migrations.CreateModel(
            name="PurchaseOrderApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("level", models.PositiveSmallIntegerField(choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")])),
                ("approved_net_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("approved_gross_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="purchase_entrys.purchaseorder")),
            ],
            options={"ordering": ["purchase_order_id", "level"], "abstract": False, "unique_together": {("purchase_order", "level")}},
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("document_type", models.CharField(max_length=100)),
                ("document_name", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="procurement/purchase-requisitions/documents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase_requisition", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="purchase_entrys.purchaserequisition")),
            ],
            options={"ordering": ["-created_at", "-id"], "abstract": False},
        ),
        migrations.CreateModel(
            name="GRN",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("grn_number", models.CharField(blank=True, max_length=100, unique=True)),
                ("company_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("project_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_name", models.CharField(blank=True, max_length=255, null=True)),
                ("items_data", models.JSONField(blank=True, default=list)),
                ("invoice_date", models.DateField()),
                ("supplier_invoice_no", models.CharField(max_length=100)),
                ("eway_bill_no", models.CharField(blank=True, max_length=100, null=True)),
                ("eway_bill_date", models.DateField(blank=True, null=True)),
                ("dc_no", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("checked", "Checked"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level1_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level1_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level1_remarks", models.TextField(blank=True, null=True)),
                ("level2_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level2_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level2_remarks", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level1_approved_by_id", models.IntegerField(blank=True, null=True)),
                ("level2_checked_by_id", models.IntegerField(blank=True, null=True)),
                ("po", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="purchase_entrys.purchaseorder")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SRN",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("srn_number", models.CharField(blank=True, max_length=100, unique=True)),
                ("company_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("project_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("supplier_name", models.CharField(blank=True, max_length=255, null=True)),
                ("items_data", models.JSONField(blank=True, default=list)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("invoice_date", models.DateField()),
                ("tax_invoice_date", models.DateField(blank=True, null=True)),
                ("supplier_invoice_no", models.CharField(max_length=100)),
                ("tax_invoice_no", models.CharField(blank=True, max_length=100, null=True)),
                ("eway_bill_no", models.CharField(blank=True, max_length=100, null=True)),
                ("eway_bill_date", models.DateField(blank=True, null=True)),
                ("dc_no", models.CharField(blank=True, max_length=100, null=True)),
                ("delivery_challan_no", models.CharField(blank=True, max_length=100, null=True)),
                ("vehicle_no", models.CharField(blank=True, max_length=100, null=True)),
                ("transporter", models.CharField(blank=True, max_length=255, null=True)),
                ("received_at", models.CharField(max_length=255)),
                ("original_invoice", models.BooleanField(default=False)),
                ("oem_manual", models.BooleanField(default=False)),
                ("delivery_challan", models.BooleanField(default=False)),
                ("test_certificate", models.BooleanField(default=False)),
                ("amd_no", models.CharField(blank=True, max_length=100, null=True)),
                ("cost_center", models.CharField(blank=True, max_length=100, null=True)),
                ("basic", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("paf", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("freight_charges", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("other_charges", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_gst", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("round_off", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("checked", "Checked"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level1_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level1_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level1_remarks", models.TextField(blank=True, null=True)),
                ("level2_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("level2_approved_at", models.DateTimeField(blank=True, null=True)),
                ("level2_remarks", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level1_approved_by_id", models.IntegerField(blank=True, null=True)),
                ("level2_approved_by_id", models.IntegerField(blank=True, null=True)),
                ("po", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="purchase_entrys.purchaseorder")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SRNItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("item_code", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                ("order_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("previously_received_qty", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("received_qty", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount_type", models.CharField(blank=True, max_length=50, null=True)),
                ("discount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("srn", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="purchase_entrys.srn")),
            ],
            options={"abstract": False},
        ),
    ]
