# Generated by Django 6.0.3 on 2026-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCycle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('from_day', models.PositiveSmallIntegerField()),
                ('to_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_day_flag', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pay_cycle',
            },
        ),
    ]
