# Generated by Django 6.0.3 on 2026-06-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0002_paycycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('salary_category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'salary_category',
            },
        ),
    ]
