# Generated by Django 6.0.3 on 2026-06-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_master', '0003_salarycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('band_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('acc_year', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('sess_user_type', models.CharField(max_length=50)),
                ('sess_user_id', models.CharField(max_length=50)),
                ('sess_company_id', models.CharField(max_length=50)),
                ('sess_branch_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'band_master',
            },
        ),
    ]
